name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🚀 Install uv
        uses: astral-sh/setup-uv@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Copy data files to notebooks/public
        run: |
           mkdir -p notebooks/public
           cp results/smartbugs/data_analysis/all_patches_stats.csv notebooks/public/
           ls -la notebooks/public/  # Verify the copy worked
          

      - name: 🛠️ Export notebooks
        run: |
          python scripts/build.py

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
